#baseURL = "http://example.com/"
relativeurls = true
publishDir = "../docs/"
languageCode = "en-us"
theme = "minimal"
title = "Digital Contact Tracing"
#disqusShortname = "username" # delete this to disable disqus comments
#googleAnalytics = ""

[params]
    description = "Location Tracking, Contact Tracing, and Geospatial Privacy During COVID-19"
    githubUsername = "#"
    accent = "maroon"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    favicon = "favicon.png"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    identifier = "about"
    url = ""
    name = "About"
    weight = 2

[[menu.main]]
    parent = "about"
    url = "/aboutproject/"
    name = "About the Project"
    weight = 1
    
[[menu.main]]
    parent = "about"
    url = "/aboutteam/"
    name = "About the Team"
    weight = 2

[[menu.main]]
    identifier = "updates"
    url = ""
    name = "Updates"
    weight = 3
    
[[menu.main]]
    parent = "updates"
    url = "/press/"
    name = "Press Updates"
    weight = 1
    
[[menu.main]]
    parent = "updates"
    url = "/projectupdates/"
    name = "Project Updates"
    weight = 2
    
[[menu.main]]
    url = "/statestatus/"
    name = "State Status"
    weight = 4
    
[[menu.main]]
    url = "/technologies/"
    name = "Technologies"
    weight = 5
    
[[menu.main]]
    url = "/contact/"
    name = "Contact Us"
    weight = 6


# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://twitter.com/DigitalTracing"
    identifier = "twitter"
    name = "Twitter"
    weight = 1
    
[[menu.icon]]
    url = "https://github.com/Peter-Kedron/COVID-19-Geospatial-Technologies-For-Digital-Contact-Tracing"
    identifier = "github"
    name = "GitHub"
    weight = 2
    
[[menu.icon]]
    url = "https://osf.io/kpvbq/"
    identifier = "database"
    name = "OSF"
    weight = 3
