---
title: "About"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Location Tracking, Contact Tracing, and Geospatial Privacy of COVID-19
We are creating a database of the digital contact tracing technologies (DCTT) being used by public health authorities (PHA) in the United States to respond to the spread of SARS-COV-2, the virus responsible for COVID-19.  While we collect data on many aspects of each individual DCTT, we are particularly interested in the geospatial technologies used in these systems, the location data they produce, and how that data is managed, stored, transferred, and shared. Our project team uses this data to **assess the technological limits of DCTT, consider their privacy implications, and examine when they are likely to be most effective**. We hope the data and publications contained here will contribute to an informed public debate about the role DCTT can play during different phases of the pandemic. 

Project datasets, data collection protocols, assessment frameworks, white papers, and other publications are available for download at the [Project GitHub Repository](https://github.com/Peter-Kedron/COVID-19-Geospatial-Technologies-For-Digital-Contact-Tracing) and the [Project Open Science Framework Page](https://osf.io/kpvbq/).

This project is funded by the [U.S. National Science Foundation Award BCS-2032203](https://www.nsf.gov/awardsearch/showAward?AWD_ID=2032203).